const PROFILE_FETCH_START = 'PROFILE_FETCH_START';
const PROFILE_FETCH_DONE = 'PROFILE_FETCH_DONE';
const PROFILE_FETCH_ERROR = 'PROFILE_FETCH_ERROR';
const PROFILE_REFRESH = 'REFRESH_PROFILE';

export {
    PROFILE_FETCH_START,
    PROFILE_FETCH_DONE,
    PROFILE_FETCH_ERROR,
    PROFILE_REFRESH
}
