const PROFILE_FETCH_START = 'PROFILE_FETCH_START';
const PROFILE_FETCH_DONE = 'PROFILE_FETCH_DONE';
const PROFILE_FETCH_ERROR = 'PROFILE_FETCH_ERROR';
const PROFILE_REFRESH = 'REFRESH_PROFILE';
const POST_ADDED = 'POST_ADDED';
const POST_LIKED = 'POST_LIKED';
const APPEND_COMMENT = 'APPEND_COMMENT';
const COMMENT_LIKED = 'COMMENT_LIKED';
const DEVICE_SETTINGS = 'DEVICE_SETTINGS';

export {
    PROFILE_FETCH_START,
    PROFILE_FETCH_DONE,
    PROFILE_FETCH_ERROR,
    PROFILE_REFRESH,
    POST_ADDED,
    POST_LIKED,
    APPEND_COMMENT,
    COMMENT_LIKED,
    DEVICE_SETTINGS
}
