const timeZones = [
    {'value':'Pacific/Midway'       ,'name' : "(GMT-11:00) Midway Island"},
    {'value':'US/Samoa'             ,'name' : "(GMT-11:00) Samoa"},
    {'value':'US/Hawaii'            ,'name' : "(GMT-10:00) Hawaii"},
    {'value':'US/Alaska'            ,'name' : "(GMT-09:00) Alaska"},
    {'value':'US/Pacific'           ,'name' : "(GMT-08:00) Pacific Time (US &amp; Canada)"},
    {'value':'America/Tijuana'      ,'name' : "(GMT-08:00) Tijuana"},
    {'value':'US/Arizona'           ,'name' : "(GMT-07:00) Arizona"},
    {'value':'US/Mountain'          ,'name' : "(GMT-07:00) Mountain Time (US &amp; Canada)"},
    {'value':'America/Chihuahua'    ,'name' : "(GMT-07:00) Chihuahua"},
    {'value':'America/Mazatlan'     ,'name' : "(GMT-07:00) Mazatlan"},
    {'value':'America/Mexico_City'  ,'name' : "(GMT-06:00) Mexico City"},
    {'value':'America/Monterrey'    ,'name' : "(GMT-06:00) Monterrey"},
    {'value':'Canada/Saskatchewan'  ,'name' : "(GMT-06:00) Saskatchewan"},
    {'value':'US/Central'           ,'name' : "(GMT-06:00) Central Time (US &amp; Canada)"},
    {'value':'US/Eastern'           ,'name' : "(GMT-05:00) Eastern Time (US &amp; Canada)"},
    {'value':'US/East-Indiana'      ,'name' : "(GMT-05:00) Indiana (East)"},
    {'value':'America/Bogota'       ,'name' : "(GMT-05:00) Bogota"},
    {'value':'America/Lima'         ,'name' : "(GMT-05:00) Lima"},
    {'value':'America/Caracas'      ,'name' : "(GMT-04:30) Caracas"},
    {'value':'Canada/Atlantic'      ,'name' : "(GMT-04:00) Atlantic Time (Canada)"},
    {'value':'America/La_Paz'       ,'name' : "(GMT-04:00) La Paz"},
    {'value':'America/Santiago'     ,'name' : "(GMT-04:00) Santiago"},
    {'value':'Canada/Newfoundland'  ,'name' : "(GMT-03:30) Newfoundland"},
    {'value':'America/Buenos_Aires' ,'name' : "(GMT-03:00) Buenos Aires"},
    {'value':'Greenland'            ,'name' : "(GMT-03:00) Greenland"},
    {'value':'Atlantic/Stanley'     ,'name' : "(GMT-02:00) Stanley"},
    {'value':'Atlantic/Azores'      ,'name' : "(GMT-01:00) Azores"},
    {'value':'Atlantic/Cape_Verde'  ,'name' : "(GMT-01:00) Cape Verde Is."},
    {'value':'Africa/Casablanca'    ,'name' : "(GMT) Casablanca"},
    {'value':'Europe/Dublin'        ,'name' : "(GMT) Dublin"},
    {'value':'Europe/Lisbon'        ,'name' : "(GMT) Lisbon"},
    {'value':'Europe/London'        ,'name' : "(GMT) London"},
    {'value':'Africa/Monrovia'      ,'name' : "(GMT) Monrovia"},
    {'value':'Europe/Amsterdam'     ,'name' : "(GMT+01:00) Amsterdam"},
    {'value':'Europe/Belgrade'      ,'name' : "(GMT+01:00) Belgrade"},
    {'value':'Europe/Berlin'        ,'name' : "(GMT+01:00) Berlin"},
    {'value':'Europe/Bratislava'    ,'name' : "(GMT+01:00) Bratislava"},
    {'value':'Europe/Brussels'      ,'name' : "(GMT+01:00) Brussels"},
    {'value':'Europe/Budapest'      ,'name' : "(GMT+01:00) Budapest"},
    {'value':'Europe/Copenhagen'    ,'name' : "(GMT+01:00) Copenhagen"},
    {'value':'Europe/Ljubljana'     ,'name' : "(GMT+01:00) Ljubljana"},
    {'value':'Europe/Madrid'        ,'name' : "(GMT+01:00) Madrid"},
    {'value':'Europe/Paris'         ,'name' : "(GMT+01:00) Paris"},
    {'value':'Europe/Prague'        ,'name' : "(GMT+01:00) Prague"},
    {'value':'Europe/Rome'          ,'name' : "(GMT+01:00) Rome"},
    {'value':'Europe/Sarajevo'      ,'name' : "(GMT+01:00) Sarajevo"},
    {'value':'Europe/Skopje'        ,'name' : "(GMT+01:00) Skopje"},
    {'value':'Europe/Stockholm'     ,'name' : "(GMT+01:00) Stockholm"},
    {'value':'Europe/Vienna'        ,'name' : "(GMT+01:00) Vienna"},
    {'value':'Europe/Warsaw'        ,'name' : "(GMT+01:00) Warsaw"},
    {'value':'Europe/Zagreb'        ,'name' : "(GMT+01:00) Zagreb"},
    {'value':'Europe/Athens'        ,'name' : "(GMT+02:00) Athens"},
    {'value':'Europe/Bucharest'     ,'name' : "(GMT+02:00) Bucharest"},
    {'value':'Africa/Cairo'         ,'name' : "(GMT+02:00) Cairo"},
    {'value':'Africa/Harare'        ,'name' : "(GMT+02:00) Harare"},
    {'value':'Europe/Helsinki'      ,'name' : "(GMT+02:00) Helsinki"},
    {'value':'Europe/Istanbul'      ,'name' : "(GMT+02:00) Istanbul"},
    {'value':'Asia/Jerusalem'       ,'name' : "(GMT+02:00) Jerusalem"},
    {'value':'Europe/Kiev'          ,'name' : "(GMT+02:00) Kyiv"},
    {'value':'Europe/Minsk'         ,'name' : "(GMT+02:00) Minsk"},
    {'value':'Europe/Riga'          ,'name' : "(GMT+02:00) Riga"},
    {'value':'Europe/Sofia'         ,'name' : "(GMT+02:00) Sofia"},
    {'value':'Europe/Tallinn'       ,'name' : "(GMT+02:00) Tallinn"},
    {'value':'Europe/Vilnius'       ,'name' : "(GMT+02:00) Vilnius"},
    {'value':'Asia/Baghdad'         ,'name' : "(GMT+03:00) Baghdad"},
    {'value':'Asia/Kuwait'          ,'name' : "(GMT+03:00) Kuwait"},
    {'value':'Africa/Nairobi'       ,'name' : "(GMT+03:00) Nairobi"},
    {'value':'Asia/Riyadh'          ,'name' : "(GMT+03:00) Riyadh"},
    {'value':'Europe/Moscow'        ,'name' : "(GMT+03:00) Moscow"},
    {'value':'Asia/Tehran'          ,'name' : "(GMT+03:30) Tehran"},
    {'value':'Asia/Baku'            ,'name' : "(GMT+04:00) Baku"},
    {'value':'Europe/Volgograd'     ,'name' : "(GMT+04:00) Volgograd"},
    {'value':'Asia/Muscat'          ,'name' : "(GMT+04:00) Muscat"},
    {'value':'Asia/Tbilisi'         ,'name' : "(GMT+04:00) Tbilisi"},
    {'value':'Asia/Yerevan'         ,'name' : "(GMT+04:00) Yerevan"},
    {'value':'Asia/Kabul'           ,'name' : "(GMT+04:30) Kabul"},
    {'value':'Asia/Karachi'         ,'name' : "(GMT+05:00) Karachi"},
    {'value':'Asia/Tashkent'        ,'name' : "(GMT+05:00) Tashkent"},
    {'value':'Asia/Kolkata'         ,'name' : "(GMT+05:30) Kolkata"},
    {'value':'Asia/Kathmandu'       ,'name' : "(GMT+05:45) Kathmandu"},
    {'value':'Asia/Yekaterinburg'   ,'name' : "(GMT+06:00) Ekaterinburg"},
    {'value':'Asia/Almaty'          ,'name' : "(GMT+06:00) Almaty"},
    {'value':'Asia/Dhaka'           ,'name' : "(GMT+06:00) Dhaka"},
    {'value':'Asia/Novosibirsk'     ,'name' : "(GMT+07:00) Novosibirsk"},
    {'value':'Asia/Bangkok'         ,'name' : "(GMT+07:00) Bangkok"},
    {'value':'Asia/Jakarta'         ,'name' : "(GMT+07:00) Jakarta"},
    {'value':'Asia/Krasnoyarsk'     ,'name' : "(GMT+08:00) Krasnoyarsk"},
    {'value':'Asia/Chongqing'       ,'name' : "(GMT+08:00) Chongqing"},
    {'value':'Asia/Hong_Kong'       ,'name' : "(GMT+08:00) Hong Kong"},
    {'value':'Asia/Kuala_Lumpur'    ,'name' : "(GMT+08:00) Kuala Lumpur"},
    {'value':'Australia/Perth'      ,'name' : "(GMT+08:00) Perth"},
    {'value':'Asia/Singapore'       ,'name' : "(GMT+08:00) Singapore"},
    {'value':'Asia/Taipei'          ,'name' : "(GMT+08:00) Taipei"},
    {'value':'Asia/Ulaanbaatar'     ,'name' : "(GMT+08:00) Ulaan Bataar"},
    {'value':'Asia/Urumqi'          ,'name' : "(GMT+08:00) Urumqi"},
    {'value':'Asia/Irkutsk'         ,'name' : "(GMT+09:00) Irkutsk"},
    {'value':'Asia/Seoul'           ,'name' : "(GMT+09:00) Seoul"},
    {'value':'Asia/Tokyo'           ,'name' : "(GMT+09:00) Tokyo"},
    {'value':'Australia/Adelaide'   ,'name' : "(GMT+09:30) Adelaide"},
    {'value':'Australia/Darwin'     ,'name' : "(GMT+09:30) Darwin"},
    {'value':'Asia/Yakutsk'         ,'name' : "(GMT+10:00) Yakutsk"},
    {'value':'Australia/Brisbane'   ,'name' : "(GMT+10:00) Brisbane"},
    {'value':'Australia/Canberra'   ,'name' : "(GMT+10:00) Canberra"},
    {'value':'Pacific/Guam'         ,'name' : "(GMT+10:00) Guam"},
    {'value':'Australia/Hobart'     ,'name' : "(GMT+10:00) Hobart"},
    {'value':'Australia/Melbourne'  ,'name' : "(GMT+10:00) Melbourne"},
    {'value':'Pacific/Port_Moresby' ,'name' : "(GMT+10:00) Port Moresby"},
    {'value':'Australia/Sydney'     ,'name' : "(GMT+10:00) Sydney"},
    {'value':'Asia/Vladivostok'     ,'name' : "(GMT+11:00) Vladivostok"},
    {'value':'Asia/Magadan'         ,'name' : "(GMT+12:00) Magadan"},
    {'value':'Pacific/Auckland'     ,'name' : "(GMT+12:00) Auckland"},
    {'value':'Pacific/Fiji'         ,'name' : "(GMT+12:00) Fiji"}
];

export default timeZones;