const FRIENDSHIP_NONE = 'FRIENDSHIP_NONE';
const FRIENDSHIP_SUBSCRIBED = 'FRIENDSHIP_SUBSCRIBED';
const FRIENDSHIP_FOLLOWING = 'FRIENDSHIP_FOLLOWING';
const FRIENDSHIP_FRIENDS = 'FRIENDSHIP_FRIENDS';

export {
    FRIENDSHIP_NONE,
    FRIENDSHIP_SUBSCRIBED,
    FRIENDSHIP_FOLLOWING,
    FRIENDSHIP_FRIENDS
}